#!/bin/bash
# Resolve GEMINI_SITE and compose the container's environment file.
# Run as ExecStartPre; writes /run/tsrs-web.env, which the unit passes to
# `docker run --env-file`.
#
# One RPM serves both telescopes: the site decides which address set is used.
#
# Resolution order, first match wins:
#   1. TSRS_SITE in /etc/sysconfig/tsrs-web   -- explicit, for odd hosts
#   2. $GEMINI_SITE inherited from systemd    -- rarely set for services
#   3. GEMINI_SITE assigned in /etc/profile.d/*.sh or /etc/environment
#   4. MK
#
# Step 3 exists because GEMINI_SITE is a *login shell* variable and systemd
# services do not read profile.d. The assignment is scraped, not sourced --
# sourcing arbitrary profile scripts into a service would import whatever else
# they do, and they are written for interactive shells.
set -euo pipefail

SHARE=/usr/share/tsrs-screen
SYSCONF=/etc/sysconfig/tsrs-web
OUT=/run/tsrs-web.env

SITE=""
if [ -f "$SYSCONF" ]; then
    SITE=$(sed -n 's/^[[:space:]]*TSRS_SITE=[[:space:]]*\([A-Za-z][A-Za-z]*\).*/\1/p' "$SYSCONF" | tail -1)
fi
[ -n "$SITE" ] || SITE="${GEMINI_SITE:-}"
if [ -z "$SITE" ]; then
    SITE=$(grep -hsoE '^[[:space:]]*(export[[:space:]]+)?GEMINI_SITE=[A-Za-z]+' \
             /etc/profile.d/*.sh /etc/environment 2>/dev/null | tail -1 | sed 's/.*=//') || true
fi
SITE="${SITE:-MK}"
SITE=$(printf '%s' "$SITE" | tr '[:lower:]' '[:upper:]')

SITEFILE="$SHARE/site-$SITE.env"
if [ ! -f "$SITEFILE" ]; then
    echo "tsrs-web: unknown site '$SITE' -- no $SITEFILE" >&2
    echo "tsrs-web: set TSRS_SITE in $SYSCONF, or add that file" >&2
    exit 1
fi

# A site whose addresses have never been verified must not start. Falling back
# to the other telescope's IOC would render a readiness screen from the wrong
# mountain -- a display that is confidently wrong, which is the one failure this
# panel exists to prevent.
if grep -q '^TSRS_SITE_UNCONFIGURED=1' "$SITEFILE"; then
    echo "tsrs-web: site $SITE has no verified addresses yet ($SITEFILE)." >&2
    echo "tsrs-web: fill it in and confirm with: tsrs-ca-probe <ioc-ip> <pv>" >&2
    exit 1
fi

# Site defaults first, admin overrides second: docker --env-file takes the LAST
# occurrence of a key, so anything in /etc/sysconfig/tsrs-web wins.
umask 022
{
    echo "# Generated by resolve-site.sh at service start -- do not edit."
    echo "# Edit $SYSCONF (survives upgrades) or $SITEFILE."
    echo "TSRS_SITE=$SITE"
    cat "$SITEFILE"
    [ -f "$SYSCONF" ] && cat "$SYSCONF"
} | grep -v '^TSRS_SITE_UNCONFIGURED' > "$OUT"

echo "tsrs-web: site $SITE"
